[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
[project.urls]
Documentation = "https://datalib-ha.readthedocs.io"
Source = "https://github.com/ahmedhamila/datalib" 